CREATE TABLE `user` (
  `user_id` bigint(20) NOT NULL,
  `account_non_expired` bit(1) DEFAULT NULL,
  `credentials_non_expired` bit(1) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `enabled` bit(1) DEFAULT NULL,
  `lastname` varchar(255) DEFAULT NULL,
  `locked` bit(1) DEFAULT NULL,
  `mobile` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `username` varchar(255) DEFAULT NULL,
  `deleted` bit(1) DEFAULT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


CREATE TABLE `role` (
  `role_id` bigint(20) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`role_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


CREATE TABLE `user_role` (
  `user_id` bigint(20) NOT NULL,
  `role_id` bigint(20) NOT NULL,
  PRIMARY KEY (`user_id`,`role_id`),
  KEY `FKa68196081fvovjhkek5m97n3y` (`role_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;




CREATE TABLE `countries` (                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
             `id` smallint(6) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
             `capital` varchar(255) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
             `code` varchar(255) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
             `created_at` datetime DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
             `currency` varchar(255) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                
             `flag` bit(1) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
             `iso2` varchar(255) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
             `iso3` varchar(255) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
             `name` varchar(255) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
             `phonecode` varchar(255) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                               
             `updated_at` datetime DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
             PRIMARY KEY (`id`)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
           ) ENGINE=MyISAM DEFAULT CHARSET=latin1;



CREATE TABLE `states` (                                                                                                                                                                                                                                                                                                                                      
          `id` smallint(6) NOT NULL,                                                                                                                                                                                                                                                                                                                                 
          `created_at` datetime DEFAULT NULL,                                                                                                                                                                                                                                                                                                                        
          `flag` bit(1) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                
          `name` varchar(255) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                          
          `updated_at` datetime DEFAULT NULL,                                                                                                                                                                                                                                                                                                                        
          `country_id` smallint(6) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                     
          PRIMARY KEY (`id`),                                                                                                                                                                                                                                                                                                                                        
          KEY `FKskkdphjml9vjlrqn4m5hi251y` (`country_id`)                                                                                                                                                                                                                                                                                                           
        ) ENGINE=MyISAM DEFAULT CHARSET=latin1;


CREATE TABLE `cities` (                                                                                                                                                                                                                                                                                                                                                                                                                           
          `id` int(11) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                          
          `created_at` datetime DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                             
          `flag` bit(1) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                     
          `name` varchar(255) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                               
          `updated_on` datetime DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                             
          `country_id` smallint(6) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                          
          `state_id` smallint(6) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                            
          PRIMARY KEY (`id`),                                                                                                                                                                                                                                                                                                                                                                                                                             
          KEY `FK6gatmv9dwedve82icy8wrkdmk` (`country_id`),                                                                                                                                                                                                                                                                                                                                                                                               
          KEY `FKsu54e1tlhaof4oklvv7uphsli` (`state_id`)                                                                                                                                                                                                                                                                                                                                                                                                  
        ) ENGINE=MyISAM DEFAULT CHARSET=latin1;